# Generated by Django 2.1.3 on 2018-11-02 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_group', models.CharField(max_length=30, verbose_name='试验组别')),
            ],
            options={
                'verbose_name': '试验组别',
                'verbose_name_plural': '试验组别',
            },
        ),
        migrations.CreateModel(
            name='ExpName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20, verbose_name='试验名称')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_m2m.ExpGroup', verbose_name='试验组别')),
            ],
            options={
                'verbose_name': '试验名称',
                'verbose_name_plural': '试验名称',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=50, verbose_name='品系名称')),
                ('line_institute', models.CharField(max_length=50, verbose_name='选育单位')),
                ('line_owner', models.CharField(max_length=10, verbose_name='选育人')),
                ('line_contactor', models.CharField(max_length=10, verbose_name='联系人')),
                ('line_type', models.CharField(max_length=10, verbose_name='品种类型')),
                ('line_parents', models.CharField(max_length=50, verbose_name='亲本组合')),
                ('line_target_date', models.DateField(verbose_name='育成日期')),
                ('line_phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('line_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('test_group', models.ForeignKey(default='生产试验', on_delete=django.db.models.deletion.CASCADE, to='test_m2m.ExpGroup', verbose_name='试验名称')),
                ('test_name', models.ForeignKey(default='普通组', on_delete=django.db.models.deletion.CASCADE, to='test_m2m.ExpName', verbose_name='试验组别')),
            ],
            options={
                'verbose_name': '参试品种',
                'verbose_name_plural': '参试品种',
            },
        ),
    ]
