# Generated by Django 2.1.3 on 2018-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_m2m', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_unit', models.CharField(max_length=40, verbose_name='承试单位')),
                ('testPoint_name', models.CharField(max_length=40, verbose_name='试点名称')),
                ('testPoint_loc', models.CharField(max_length=20, verbose_name='所在地')),
                ('testLoc_longitude', models.CharField(max_length=10, verbose_name='经度')),
                ('testLoc_latitude', models.CharField(max_length=10, verbose_name='纬度')),
                ('testLoc_altitude', models.CharField(max_length=10, verbose_name='海拔')),
                ('address', models.TextField(verbose_name='通讯地址')),
                ('contacts', models.CharField(max_length=10, verbose_name='联系人')),
                ('contact_num', models.CharField(max_length=15, verbose_name='联系电话')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('test_group', models.ManyToManyField(to='test_m2m.ExpGroup', verbose_name='试验组别')),
                ('test_name', models.ManyToManyField(to='test_m2m.ExpName', verbose_name='试验名称')),
            ],
            options={
                'verbose_name': '承试单位',
                'verbose_name_plural': '承试单位',
            },
        ),
    ]
