# Generated by Django 2.1.3 on 2018-11-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_m2m', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='低荚高')),
                ('weight_HGrain', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='百粒重')),
                ('rate_PurpleSpot', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='紫斑率')),
                ('rate_BrownSpot', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='褐斑率')),
                ('rate_Insect', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='虫食率')),
                ('rate_others', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='其他粒率')),
                ('remarks', models.TextField(verbose_name='备注')),
                ('line_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_m2m.Line', verbose_name='品系名称')),
            ],
            options={
                'verbose_name': '经济性状',
                'verbose_name_plural': '经济性状',
            },
        ),
        migrations.CreateModel(
            name='FieldCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeding_date', models.DateField(verbose_name='播种期')),
                ('seeding_state', models.DateField(verbose_name='出苗期')),
                ('flowering_period', models.DateField(verbose_name='开花期')),
                ('mature_period', models.DateField(verbose_name='成熟期')),
                ('harvest_period', models.DateField(verbose_name='收获期')),
                ('No_GrowDays', models.PositiveIntegerField(verbose_name='生育日数')),
                ('leaf_shape', models.CharField(choices=[('圆叶', '圆叶'), ('卵圆', '卵圆'), ('椭圆', '椭圆'), ('披针形', '披针形')], max_length=5, verbose_name='叶形')),
                ('flower_color', models.CharField(choices=[('白花', '白花'), ('紫花', '紫花')], max_length=5, verbose_name='花色')),
                ('hairy_color', models.CharField(choices=[('灰色', '灰色'), ('灰色', '灰色')], max_length=5, verbose_name='茸毛色')),
                ('pod_BearHabit', models.CharField(choices=[('有限', '有限'), ('亚有限', '亚有限'), ('无限', '无限')], max_length=8, verbose_name='结荚习性')),
                ('plant_architecture', models.CharField(choices=[('收敛', '收敛'), ('开张', '开张'), ('半开张', '半开张')], max_length=8, verbose_name='株型')),
                ('pod_dehiscence', models.CharField(choices=[('不裂', '不裂'), ('中裂', '中裂'), ('易裂', '易裂')], max_length=5, verbose_name='裂荚性')),
                ('deciduous', models.CharField(choices=[('落叶', '落叶'), ('半落', '半落'), ('不落', '不落')], max_length=5, verbose_name='落叶性')),
                ('lodging', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=2, verbose_name='倒伏性')),
                ('root_rot', models.CharField(max_length=5, verbose_name='根腐病')),
                ('smv', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=5, verbose_name='花叶病')),
                ('in_green', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='症青')),
                ('virus_other', models.CharField(max_length=50, verbose_name='其他病毒病')),
                ('line_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_m2m.Line', verbose_name='参试品系')),
            ],
            options={
                'verbose_name': '田间性状',
                'verbose_name_plural': '田间性状',
            },
        ),
    ]
