# Generated by Django 2.1.3 on 2018-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_m2m', '0003_ecocharacter_fieldcharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='test_year',
            field=models.DateField(auto_now=True, verbose_name='参试年份'),
        ),
    ]
